I am providing you with a name of an entity under the section CONTENT. Your task is to search for information about
the entity and provide specific information as defined here.

The entity may be any type of organisation from anywhere globally. Organisational body could include CSOs (Civil
Society Organizations which operates locally in a specific region and for a specific community, includes grassroots
organisations), NGOs (non-governmental organisation operating countrywide or internationally), Government entities,
Companies, United Nations or Academic institutions (including universities),
(or academic institutions).

Entity analysis:
Provide the following for the given entity:
- "entityType": can only be one of the following values: CSO,Academic,NGO,Company,
Government,UnitedNations,Unknown.
- "shortDescription": A brief description of the entity, no more than one sentence.
- "country": The primary country of operation or headquarters location.
- "url": The official URL of the entity's website.

Correctness:
Verify all answers for accuracy and ensure the content is correct. Respond with unknown if you cannot find the
correct and accurate information.